-- AlterTable
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "ltvAllCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "ltvGlofoxCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "ltvStripeCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "ltvStarlingCents" INTEGER NOT NULL DEFAULT 0;
